// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Application = sequelize.define('application', {
    status: {
      type: DataTypes.ENUM('리뷰 진행중','리뷰 종료'),
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'application',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Application.associate = (models) => {
    Application.belongsTo(models.requestPost, {
      foreignKey: {
        name: 'requestPostIdKey',
        field: 'RequestPostId',
      },
      as: 'requestPost',
    });
    Application.belongsTo(models.programmer, {
      foreignKey: {
        name: 'programmerIdKey',
        field: 'ProgrammerId',
      },
      as: 'programmer',
    });
    Application.hasMany(models.comment, {
      foreignKey: {
        name: 'applicationIdKey',
        field: 'ApplicationId',
      },
      as: 'comments',
    });
  };

  return Application;
};
