// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Comment = sequelize.define('comment', {
    content: {
      type: DataTypes.STRING,
    },
    position: {
      type: DataTypes.ENUM('student','programmer'),
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'comment',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Comment.associate = (models) => {
    Comment.belongsTo(models.user, {
      foreignKey: {
        name: 'userIdKey',
        field: 'UserId',
      },
      as: 'user',
    });
    Comment.belongsTo(models.requestPost, {
      foreignKey: {
        name: 'requestPostIdKey',
        field: 'RequestPostId',
      },
      as: 'requestPost',
    });
    Comment.belongsTo(models.application, {
      foreignKey: {
        name: 'applicationIdKey',
        field: 'ApplicationId',
      },
      as: 'application',
    });
  };

  return Comment;
};
