// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const RequestPost = sequelize.define('requestPost', {
    title: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    body: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    maxReviewer: {
      type: DataTypes.INTEGER,
      defaultValue: 1,
    },
    file: {
      type: DataTypes.STRING,
    },
    status: {
      type: DataTypes.ENUM('recurit','ing','end'),
      defaultValue: "recurit",
    },
    type: {
      type: DataTypes.ENUM('portfolio','resume','consulting'),
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'requestPost',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  RequestPost.associate = (models) => {
    RequestPost.belongsTo(models.user, {
      foreignKey: {
        name: 'userIdKey',
        field: 'UserId',
      },
      as: 'user',
    });
    RequestPost.belongsToMany(models.programmer, {
      through: 'requestReview',
      foreignKey: 'RequestPostId',
      otherKey: 'ProgrammerId',
      as: 'programmerThroughRequestReviews',
    });
    RequestPost.hasMany(models.application, {
      foreignKey: {
        name: 'requestPostIdKey',
        field: 'RequestPostId',
      },
      as: 'applications',
    });
    RequestPost.hasMany(models.comment, {
      foreignKey: {
        name: 'requestPostIdKey',
        field: 'RequestPostId',
      },
      as: 'comments',
    });
    RequestPost.hasMany(models.file, {
      foreignKey: {
        name: 'requestPostIdKey',
        field: 'RequestPostId',
      },
      as: 'files',
    });
  };

  return RequestPost;
};
