// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const RequestReview = sequelize.define('requestReview', {
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    requestPostId: {
      type: DataTypes.INTEGER,
      field: 'RequestPostId',
      primaryKey: true,
      allowNull: false,
    },
    programmerId: {
      type: DataTypes.INTEGER,
      field: 'ProgrammerId',
      primaryKey: true,
      allowNull: false,
    },
  }, {
    tableName: 'RequestReview',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  RequestReview.associate = (models) => {
    RequestReview.belongsTo(models.requestPost, {
      foreignKey: {
        name: 'requestPostIdKey',
        field: 'RequestPostId',
      },
      as: 'requestPost',
    });
    RequestReview.belongsTo(models.programmer, {
      foreignKey: {
        name: 'programmerIdKey',
        field: 'ProgrammerId',
      },
      as: 'programmer',
    });
  };

  return RequestReview;
};
